[project]
name = "vscode-python"
version = "0.1.0"
description = "Example VSCode Python project"
readme = "README.md"
requires-python = ">=3.13"

[tool.pytest.ini_options]
# List of dirs to look for Python modules
pythonpath = "src"

[dependency-groups]
dev = ["pytest>=8.3.3"]
